// AUTO-GENERATED by scripts/build-migrations.mjs — do not edit.
// Regenerate with `pnpm db:generate` after changing the schema.

const bundle = {
  "journal": {
    "entries": [
      {
        "idx": 0,
        "when": 1785604404855,
        "tag": "0000_flat_red_ghost",
        "breakpoints": true
      }
    ]
  },
  "migrations": {
    "m0000": "CREATE TABLE `outbox` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`entity_type` text NOT NULL,\n\t`entity_id` text NOT NULL,\n\t`op_type` text NOT NULL,\n\t`payload` text,\n\t`status` text DEFAULT 'pending' NOT NULL,\n\t`attempts` integer DEFAULT 0 NOT NULL,\n\t`last_error` text,\n\t`batch_id` text,\n\t`client_created_at_utc` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `outbox_status_client_created_idx` ON `outbox` (`status`,`client_created_at_utc`);--> statement-breakpoint\nCREATE INDEX `outbox_entity_idx` ON `outbox` (`entity_type`,`entity_id`);--> statement-breakpoint\nCREATE TABLE `sync_meta` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value` text NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL\n);\n"
  }
};

export default bundle;
